# Lab 6 (Part 1)

## Principal Component Analysis Implementation from scratch

## 10th March 2021

In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [11]:
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("A")
print(A)
print("--------------------------")

# calculate the mean of each column
M = mean(A.T, axis=1)
print(" ")
print("Mean of each column")
print(M)
print("--------------------------")

# center columns by subtracting column means
C = A - M
print(" ")
print("Center of columns by subtracting column means")
print(C)
print("--------------------------")

# calculate covariance matrix of centered matrix
V = cov(C.T)
print(" ")
print("Covariance of centered matrix")
print(V)
print("--------------------------")

# eigendecomposition of covariance matrix
values, vectors = eig(V)
print("")
print("Eigenvectors:")
print(vectors)
print("--------------------------")
print("Eigenvalues")
print(values)
print("")
print("--------------------------")

# project data
P = vectors.T.dot(C.T)
print(" ")
print("Projected Data")
print(P.T)
print("--------------------------")

A
[[1 2]
 [3 4]
 [5 6]]
--------------------------
 
Mean of each column
[3. 4.]
--------------------------
 
Center of columns by subtracting column means
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
--------------------------
 
Covariance of centered matrix
[[4. 4.]
 [4. 4.]]
--------------------------

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
--------------------------
Eigenvalues
[8. 0.]

--------------------------
 
Projected Data
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
--------------------------
